services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_orders_php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - postgres
      - redis
    tty: true
    stdin_open: true

  postgres:
    image: postgres:17-alpine
    container_name: laravel_orders_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password

  redis:
    image: redis:7-alpine
    container_name: laravel_orders_redis
    ports:
      - "6379:6379"
